local colors = require("config.colors")
require("scrollbar").setup({
    show = true,
    show_in_active_only = false,
    set_highlights = true,
    folds = 1000,
    max_lines = false,
    hide_if_all_visible = false,
    throttle_ms = 100,
    handle = {
        color = colors.bg_highlight,
        text = " ",
        highlight = "CursorColumn",
        hide_if_all_visible = true,
    },
    marks = {
        Cursor = { text = "•", priority = 0, gui=nil, highlight = "Normal", },
        Search = { text = { "-", "=" }, color = colors.orange, priority = 1, gui=nil, highlight = "Search", },
        Error = { text = { "-", "=" }, priority = 2, gui=nil, color = colors.error, highlight = "DiagnosticVirtualTextError", },
        Warn = { text = { "-", "=" }, priority = 3, gui=nil, color = colors.warning, highlight = "DiagnosticVirtualTextWarn", },
        Info = { text = { "-", "=" }, priority = 4, gui=nil, color = colors.info, highlight = "DiagnosticVirtualTextInfo", },
        Hint = { text = { "-", "=" }, priority = 5, gui=nil, color = colors.hint, highlight = "DiagnosticVirtualTextHint", },
        Misc = { text = { "-", "=" }, priority = 6, gui=nil, color = colors.purple, highlight = "Normal", },
        GitAdd = { text = "┆", priority = 7, gui=nil, highlight = "GitSignsAdd", },
        GitChange = { text = "┆", priority = 7, gui=nil, highlight = "GitSignsChange", },
        GitDelete = { text = "▁", priority = 7, gui=nil, highlight = "GitSignsDelete", },
    },
    excluded_buftypes = {"terminal", "telescope", "nofile"},
    excluded_filetypes = {"prompt", "help", "dashboard", "packer", "NvimTree", "Trouble", "TelescopePrompt", "Float"},
    autocmd = {
        render = { "BufWinEnter", "TabEnter", "TermEnter", "WinEnter", "CmdwinLeave", "TextChanged", "VimResized", "WinScrolled", },
        clear = { "BufWinLeave", "TabLeave", "TermLeave", "WinLeave", },
    },
    handlers = {
        cursor = true,
        diagnostic = true,
        gitsigns = true,
        handle = true,
        search = false,
        ale = false,
    },
})
