require('smoothcursor').setup({
    autostart = true,
    cursor = " ▷",              
    texthl = "SmoothCursor",   
    linehl = nil,              
    type = "default",          
    fancy = { enable = true, head = { cursor = " ▷", texthl = "SmoothCursor", linehl = nil }, body = {}, tail = { cursor = nil, texthl = "SmoothCursor" } },
    flyin_effect = nil,        
    speed = 25,                
    intervals = 35,            
    priority = 10,             
    timeout = 3000,            
    threshold = 3,             
    disable_float_win = true, 
    enabled_filetypes = nil,  
    disabled_filetypes =  {"prompt", "DiffviewFilePanel",  "help", "dashboard", "packer", "NvimTree", "Trouble", "TelescopePrompt", "Float"},  
})